apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wmxm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wmxm
    app.kubernetes.io/part-of: byoc-app-srtf
  name: wmxm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: wmxm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: wmxm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-kifv-tenant/byoc-app-srtf/wmxm@sha256:e78e92d5e21195e81cec74376172b0cc491c89c43be6a2ba57221ee3b0f0d2b5
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
